# Generated by Django 3.1.4 on 2021-03-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Product_Name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Stock', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
