# Generated by Django 3.1.4 on 2021-03-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetailApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
