# Generated by Django 3.1.4 on 2021-03-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetailApp', '0003_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer1',
        ),
    ]
