# Generated by Django 3.1.4 on 2021-03-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetailApp', '0005_auto_20210320_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='tb_Customer',
        ),
    ]
