# Generated by Django 3.1.4 on 2021-04-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetailApp', '0006_auto_20210320_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
