# Generated by Django 3.1.4 on 2021-05-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prdct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(max_length=20, upload_to='')),
            ],
        ),
    ]
