# Generated by Django 3.1.4 on 2021-05-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdct',
            name='Image',
            field=models.ImageField(upload_to=None),
        ),
    ]
